In [1]:
# import the library

import numpy as np

In [2]:
arr = np.array([45,57,43,7])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr1 = np.array([45,67,44,90,'Aditya'])
arr1

array(['45', '67', '44', '90', 'Aditya'], dtype='<U21')

In [7]:
ar = np.array(['Adi'])
ar

array(['Adi'], dtype='<U3')

In [8]:
ar.dtype

dtype('<U3')

In [9]:
print(arr1)

['45' '67' '44' '90' 'Aditya']


In [10]:
%%timeit 
arr2 = np.array([34,56,23])

1.29 µs ± 54.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
%%timeit
a = [34,56,23]

100 ns ± 4.68 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [12]:
B = [56,45,66.77,'Aditya']

In [16]:
arr2

array([1, 2, 3, 4])

In [17]:
arr2 = np.arange(1,7)
arr2

array([1, 2, 3, 4, 5, 6])

In [18]:
arr = np.arange(1,20,0.75)
arr

array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ,  4.75,  5.5 ,  6.25,  7.  ,
        7.75,  8.5 ,  9.25, 10.  , 10.75, 11.5 , 12.25, 13.  , 13.75,
       14.5 , 15.25, 16.  , 16.75, 17.5 , 18.25, 19.  , 19.75])

In [19]:
arr2 = np.arange(1,7,2)

In [20]:
arr2

array([1, 3, 5])

In [21]:
arr2 = np.array(range(1,20,0.75))

TypeError: 'float' object cannot be interpreted as an integer

In [22]:
arr2 = np.arange(1,7,2)

In [23]:
arr2.ndim

1

In [24]:
arr2

array([1, 3, 5])

In [25]:
arr2[2]

5

In [28]:
arr2 = np.append(arr2,60)

In [29]:
arr2

array([ 1,  3,  5, 60])

In [30]:
np.insert(arr2, 2, 10)

array([ 1,  3, 10,  5, 60])

In [35]:
arr3 = np.array([[45,56,78,45],[67,89,34,90]])
arr3;

In [36]:
print(arr3)

[[45 56 78 45]
 [67 89 34 90]]


In [37]:
arr3.ndim

2

In [41]:
arr3[0,1]

56

In [43]:
arr3[1,:2]

array([67, 89])

In [44]:
arr3 = np.array([[45,56,78,45],[67,89,34,90],[34,23,56,78]])
arr3

array([[45, 56, 78, 45],
       [67, 89, 34, 90],
       [34, 23, 56, 78]])

In [46]:
arr3[1:3, :3]

array([[67, 89, 34],
       [34, 23, 56]])

In [47]:
arr3.shape

(3, 4)

In [48]:
arr3.size

12

In [49]:
arr3.reshape(6,2)

array([[45, 56],
       [78, 45],
       [67, 89],
       [34, 90],
       [34, 23],
       [56, 78]])

In [51]:
arr3 = arr3.reshape(6,-1)

In [52]:
arr3

array([[45, 56],
       [78, 45],
       [67, 89],
       [34, 90],
       [34, 23],
       [56, 78]])

In [53]:
arr4 = arr3.reshape(6,2)

In [54]:
arr4

array([[45, 56],
       [78, 45],
       [67, 89],
       [34, 90],
       [34, 23],
       [56, 78]])

In [55]:
l = []

for i in range(5):
    i = int(input('enter the number'))
    l.append(i)
    
print(np.array(l))

enter the number45
enter the number56
enter the number43
enter the number23
enter the number67
[45 56 43 23 67]
